import { Lib } from "./definition";

export const data: Lib[] = [
  {
    kind: "Hiragana",
    letters: [
      { text: "あ", prounounce: "a", unicode: "\u3042", art: "NotCreated" },
      { text: "い", prounounce: "i", unicode: "\u3044", art: "NotCreated" },
      { text: "う", prounounce: "u", unicode: "\u3046", art: "NotCreated" },
      { text: "え", prounounce: "e", unicode: "\u3048", art: "NotCreated" },
      { text: "お", prounounce: "o", unicode: "\u304A", art: "NotCreated" },
      { text: "か", prounounce: "ka", unicode: "\u304B", art: "NotCreated" },
      { text: "き", prounounce: "ki", unicode: "\u304D", art: "NotCreated" },
      { text: "く", prounounce: "ku", unicode: "\u304F", art: "NotCreated" },
      { text: "け", prounounce: "ke", unicode: "\u3051", art: "NotCreated" },
      { text: "こ", prounounce: "ko", unicode: "\u3053", art: "NotCreated" },
      { text: "さ", prounounce: "sa", unicode: "\u3055", art: "NotCreated" },
      { text: "し", prounounce: "shi", unicode: "\u3057", art: "NotCreated" },
      { text: "す", prounounce: "su", unicode: "\u3059", art: "NotCreated" },
      { text: "せ", prounounce: "se", unicode: "\u305B", art: "NotCreated" },
      { text: "そ", prounounce: "so", unicode: "\u305D", art: "NotCreated" },
      { text: "た", prounounce: "ta", unicode: "\u305F", art: "NotCreated" },
      { text: "ち", prounounce: "chi", unicode: "\u3061", art: "NotCreated" },
      { text: "つ", prounounce: "tsu", unicode: "\u3064", art: "NotCreated" },
      { text: "て", prounounce: "te", unicode: "\u3066", art: "NotCreated" },
      { text: "と", prounounce: "to", unicode: "\u3068", art: "NotCreated" },
      { text: "な", prounounce: "na", unicode: "\u306A", art: "NotCreated" },
      { text: "に", prounounce: "ni", unicode: "\u306B", art: "NotCreated" },
      { text: "ぬ", prounounce: "nu", unicode: "\u306C", art: "NotCreated" },
      { text: "ね", prounounce: "ne", unicode: "\u306D", art: "NotCreated" },
      { text: "の", prounounce: "no", unicode: "\u306E", art: "NotCreated" },
      { text: "は", prounounce: "ha", unicode: "\u306F", art: "NotCreated" },
      { text: "ひ", prounounce: "hi", unicode: "\u3072", art: "NotCreated" },
      { text: "ふ", prounounce: "fu", unicode: "\u3075", art: "NotCreated" },
      { text: "へ", prounounce: "he", unicode: "\u3078", art: "NotCreated" },
      { text: "ほ", prounounce: "ho", unicode: "\u307B", art: "NotCreated" },
      { text: "ま", prounounce: "ma", unicode: "\u307E", art: "NotCreated" },
      { text: "み", prounounce: "mi", unicode: "\u307F", art: "NotCreated" },
      { text: "む", prounounce: "mu", unicode: "\u3080", art: "NotCreated" },
      { text: "め", prounounce: "me", unicode: "\u3081", art: "NotCreated" },
      { text: "も", prounounce: "mo", unicode: "\u3082", art: "NotCreated" },
      { text: "や", prounounce: "ya", unicode: "\u3084", art: "NotCreated" },
      { text: "ゆ", prounounce: "yu", unicode: "\u3086", art: "NotCreated" },
      { text: "よ", prounounce: "yo", unicode: "\u3088", art: "NotCreated" },
      { text: "ら", prounounce: "ra", unicode: "\u3089", art: "NotCreated" },
      { text: "り", prounounce: "ri", unicode: "\u308A", art: "NotCreated" },
      { text: "る", prounounce: "ru", unicode: "\u308B", art: "NotCreated" },
      { text: "れ", prounounce: "re", unicode: "\u308C", art: "NotCreated" },
      { text: "ろ", prounounce: "ro", unicode: "\u308D", art: "NotCreated" },
      { text: "わ", prounounce: "wa", unicode: "\u308F", art: "NotCreated" },
      { text: "を", prounounce: "wo", unicode: "\u3092", art: "NotCreated" },
      { text: "ん", prounounce: "n", unicode: "\u3093", art: "NotCreated" },
      // 濁音
      { text: "が", prounounce: "ga", unicode: "\u304C", art: "NotCreated" },
      { text: "ぎ", prounounce: "gi", unicode: "\u304E", art: "NotCreated" },
      { text: "ぐ", prounounce: "gu", unicode: "\u3050", art: "NotCreated" },
      { text: "げ", prounounce: "ge", unicode: "\u3052", art: "NotCreated" },
      { text: "ご", prounounce: "go", unicode: "\u3054", art: "NotCreated" },
      { text: "ざ", prounounce: "za", unicode: "\u3056", art: "NotCreated" },
      { text: "じ", prounounce: "ji", unicode: "\u3058", art: "NotCreated" },
      { text: "ず", prounounce: "zu", unicode: "\u305A", art: "NotCreated" },
      { text: "ぜ", prounounce: "ze", unicode: "\u305C", art: "NotCreated" },
      { text: "ぞ", prounounce: "zo", unicode: "\u305E", art: "NotCreated" },
      { text: "だ", prounounce: "da", unicode: "\u3060", art: "NotCreated" },
      { text: "ぢ", prounounce: "ji", unicode: "\u3062", art: "NotCreated" },
      { text: "づ", prounounce: "zu", unicode: "\u3065", art: "NotCreated" },
      { text: "で", prounounce: "de", unicode: "\u3067", art: "NotCreated" },
      { text: "ど", prounounce: "do", unicode: "\u3069", art: "NotCreated" },
      { text: "ば", prounounce: "ba", unicode: "\u3070", art: "NotCreated" },
      { text: "び", prounounce: "bi", unicode: "\u3073", art: "NotCreated" },
      { text: "ぶ", prounounce: "bu", unicode: "\u3076", art: "NotCreated" },
      { text: "べ", prounounce: "be", unicode: "\u3079", art: "NotCreated" },
      { text: "ぼ", prounounce: "bo", unicode: "\u307C", art: "NotCreated" },
      // 半濁音
      { text: "ぱ", prounounce: "pa", unicode: "\u3071", art: "NotCreated" },
      { text: "ぴ", prounounce: "pi", unicode: "\u3074", art: "NotCreated" },
      { text: "ぷ", prounounce: "pu", unicode: "\u3077", art: "NotCreated" },
      { text: "ぺ", prounounce: "pe", unicode: "\u307A", art: "NotCreated" },
      { text: "ぽ", prounounce: "po", unicode: "\u307D", art: "NotCreated" },
      // 拗音
      {
        text: "ゃ",
        prounounce: "small_ya",
        unicode: "\u3083",
        art: "NotCreated",
      },
      {
        text: "ゅ",
        prounounce: "small_yu",
        unicode: "\u3085",
        art: "NotCreated",
      },
      {
        text: "ょ",
        prounounce: "small_yo",
        unicode: "\u3087",
        art: "NotCreated",
      },
      // 促音
      {
        text: "っ",
        prounounce: "small_tsu",
        unicode: "\u3063",
        art: "NotCreated",
      },
    ],
  },
  {
    kind: "Katakana",
    letters: [
      // 清音
      { text: "ア", prounounce: "a", unicode: "\u30a2", art: "NotCreated" },
      {
        text: "イ",
        prounounce: "i",
        unicode: "\u30a4",
        art: "  ┏┓\n┏━┛┃\n    ┗┓┏┛\n     ┃┃\n     ┗┛\n",
      },
      { text: "ウ", prounounce: "u", unicode: "\u30a6", art: "NotCreated" },
      { text: "エ", prounounce: "e", unicode: "\u30a8", art: "NotCreated" },
      { text: "オ", prounounce: "o", unicode: "\u30aa", art: "NotCreated" },
      { text: "カ", prounounce: "ka", unicode: "\u30ab", art: "NotCreated" },
      { text: "キ", prounounce: "ki", unicode: "\u30ad", art: "NotCreated" },
      { text: "ク", prounounce: "ku", unicode: "\u30af", art: "NotCreated" },
      { text: "ケ", prounounce: "ke", unicode: "\u30b1", art: "NotCreated" },
      { text: "コ", prounounce: "ko", unicode: "\u30b3", art: "NotCreated" },
      { text: "サ", prounounce: "sa", unicode: "\u30b5", art: "NotCreated" },
      { text: "シ", prounounce: "shi", unicode: "\u30b7", art: "NotCreated" },
      { text: "ス", prounounce: "su", unicode: "\u30b9", art: "NotCreated" },
      { text: "セ", prounounce: "se", unicode: "\u30bb", art: "NotCreated" },
      { text: "ソ", prounounce: "so", unicode: "\u30bd", art: "NotCreated" },
      { text: "タ", prounounce: "ta", unicode: "\u30bf", art: "NotCreated" },
      { text: "チ", prounounce: "chi", unicode: "\u30c1", art: "NotCreated" },
      { text: "ツ", prounounce: "tsu", unicode: "\u30c4", art: "NotCreated" },
      { text: "テ", prounounce: "te", unicode: "\u30c6", art: "NotCreated" },
      { text: "ト", prounounce: "to", unicode: "\u30c8", art: "NotCreated" },
      { text: "ナ", prounounce: "na", unicode: "\u30ca", art: "NotCreated" },
      { text: "ニ", prounounce: "ni", unicode: "\u30cb", art: "NotCreated" },
      { text: "ヌ", prounounce: "nu", unicode: "\u30cc", art: "NotCreated" },
      { text: "ネ", prounounce: "ne", unicode: "\u30cd", art: "NotCreated" },
      { text: "ノ", prounounce: "no", unicode: "\u30ce", art: "NotCreated" },
      { text: "ハ", prounounce: "ha", unicode: "\u30cf", art: "NotCreated" },
      { text: "ヒ", prounounce: "hi", unicode: "\u30d2", art: "NotCreated" },
      { text: "フ", prounounce: "fu", unicode: "\u30d5", art: "NotCreated" },
      { text: "ヘ", prounounce: "he", unicode: "\u30d8", art: "NotCreated" },
      { text: "ホ", prounounce: "ho", unicode: "\u30db", art: "NotCreated" },
      { text: "マ", prounounce: "ma", unicode: "\u30de", art: "NotCreated" },
      { text: "ミ", prounounce: "mi", unicode: "\u30df", art: "NotCreated" },
      { text: "ム", prounounce: "mu", unicode: "\u30e0", art: "NotCreated" },
      { text: "メ", prounounce: "me", unicode: "\u30e1", art: "NotCreated" },
      { text: "モ", prounounce: "mo", unicode: "\u30e2", art: "NotCreated" },
      { text: "ヤ", prounounce: "ya", unicode: "\u30e4", art: "NotCreated" },
      { text: "ユ", prounounce: "yu", unicode: "\u30e6", art: "NotCreated" },
      { text: "ヨ", prounounce: "yo", unicode: "\u30e8", art: "NotCreated" },
      { text: "ラ", prounounce: "ra", unicode: "\u30e9", art: "NotCreated" },
      { text: "リ", prounounce: "ri", unicode: "\u30ea", art: "NotCreated" },
      { text: "ル", prounounce: "ru", unicode: "\u30eb", art: "NotCreated" },
      { text: "レ", prounounce: "re", unicode: "\u30ec", art: "NotCreated" },
      { text: "ロ", prounounce: "ro", unicode: "\u30ed", art: "NotCreated" },
      { text: "ワ", prounounce: "wa", unicode: "\u30ef", art: "NotCreated" },
      { text: "ヲ", prounounce: "wo", unicode: "\u30f2", art: "NotCreated" },
      { text: "ン", prounounce: "n", unicode: "\u30f3", art: "NotCreated" },
      // 濁音
      { text: "ガ", prounounce: "ga", unicode: "\u30ac", art: "NotCreated" },
      { text: "ギ", prounounce: "gi", unicode: "\u30ae", art: "NotCreated" },
      { text: "グ", prounounce: "gu", unicode: "\u30b0", art: "NotCreated" },
      { text: "ゲ", prounounce: "ge", unicode: "\u30b2", art: "NotCreated" },
      { text: "ゴ", prounounce: "go", unicode: "\u30b4", art: "NotCreated" },
      { text: "ザ", prounounce: "za", unicode: "\u30b6", art: "NotCreated" },
      { text: "ジ", prounounce: "ji", unicode: "\u30b8", art: "NotCreated" },
      { text: "ズ", prounounce: "zu", unicode: "\u30ba", art: "NotCreated" },
      { text: "ゼ", prounounce: "ze", unicode: "\u30bc", art: "NotCreated" },
      { text: "ゾ", prounounce: "zo", unicode: "\u30be", art: "NotCreated" },
      { text: "ダ", prounounce: "da", unicode: "\u30c0", art: "NotCreated" },
      { text: "ヂ", prounounce: "ji", unicode: "\u30c2", art: "NotCreated" },
      { text: "ヅ", prounounce: "zu", unicode: "\u30c5", art: "NotCreated" },
      { text: "デ", prounounce: "de", unicode: "\u30c7", art: "NotCreated" },
      { text: "ド", prounounce: "do", unicode: "\u30c9", art: "NotCreated" },
      { text: "バ", prounounce: "ba", unicode: "\u30D0", art: "NotCreated" },
      { text: "ビ", prounounce: "bi", unicode: "\u30D3", art: "NotCreated" },
      { text: "ブ", prounounce: "bu", unicode: "\u30D6", art: "NotCreated" },
      { text: "ベ", prounounce: "be", unicode: "\u30D9", art: "NotCreated" },
      { text: "ボ", prounounce: "bo", unicode: "\u30DC", art: "NotCreated" },
      // 半濁音
      { text: "パ", prounounce: "pa", unicode: "\u30D1", art: "NotCreated" },
      { text: "ピ", prounounce: "pi", unicode: "\u30D4", art: "NotCreated" },
      { text: "プ", prounounce: "pu", unicode: "\u30D7", art: "NotCreated" },
      { text: "ペ", prounounce: "pe", unicode: "\u30DA", art: "NotCreated" },
      { text: "ポ", prounounce: "po", unicode: "\u30DD", art: "NotCreated" },
      // 拗音
      {
        text: "ャ",
        prounounce: "small_ya",
        unicode: "\u30e3",
        art: "NotCreated",
      },
      {
        text: "ュ",
        prounounce: "small_yu",
        unicode: "\u30e5",
        art: "NotCreated",
      },
      {
        text: "ョ",
        prounounce: "small_yo",
        unicode: "\u30e7",
        art: "NotCreated",
      },
      // 促音
      {
        text: "ッ",
        prounounce: "small_tsu",
        unicode: "\u30C3",
        art: "NotCreated",
      },
    ],
  },
  {
    kind: "Alphabet",
    letters: [
      { text: "A", prounounce: "A", unicode: "\u0041", art: "NotCreated" },
      { text: "B", prounounce: "B", unicode: "\u0042", art: "NotCreated" },
      { text: "C", prounounce: "C", unicode: "\u0043", art: "NotCreated" },
      { text: "D", prounounce: "D", unicode: "\u0044", art: "NotCreated" },
      { text: "E", prounounce: "E", unicode: "\u0045", art: "NotCreated" },
      { text: "F", prounounce: "F", unicode: "\u0046", art: "NotCreated" },
      { text: "G", prounounce: "G", unicode: "\u0047", art: "NotCreated" },
      { text: "H", prounounce: "H", unicode: "\u0048", art: "NotCreated" },
      { text: "I", prounounce: "I", unicode: "\u0049", art: "NotCreated" },
      { text: "J", prounounce: "J", unicode: "\u004A", art: "NotCreated" },
      { text: "K", prounounce: "K", unicode: "\u004B", art: "NotCreated" },
      { text: "L", prounounce: "L", unicode: "\u004C", art: "NotCreated" },
      { text: "M", prounounce: "M", unicode: "\u004D", art: "NotCreated" },
      { text: "N", prounounce: "N", unicode: "\u004E", art: "NotCreated" },
      { text: "O", prounounce: "O", unicode: "\u004F", art: "NotCreated" },
      { text: "P", prounounce: "P", unicode: "\u0050", art: "NotCreated" },
      { text: "Q", prounounce: "Q", unicode: "\u0051", art: "NotCreated" },
      { text: "R", prounounce: "R", unicode: "\u0052", art: "NotCreated" },
      { text: "S", prounounce: "S", unicode: "\u0053", art: "NotCreated" },
      { text: "T", prounounce: "T", unicode: "\u0054", art: "NotCreated" },
      { text: "U", prounounce: "U", unicode: "\u0055", art: "NotCreated" },
      { text: "V", prounounce: "V", unicode: "\u0056", art: "NotCreated" },
      { text: "W", prounounce: "W", unicode: "\u0057", art: "NotCreated" },
      { text: "X", prounounce: "X", unicode: "\u0058", art: "NotCreated" },
      { text: "Y", prounounce: "Y", unicode: "\u0059", art: "NotCreated" },
      { text: "Z", prounounce: "Z", unicode: "\u005A", art: "NotCreated" },
    ],
  },
];
