import { Lib } from "./types/definition";

export const libFull: Lib = {
  width: "full",
  letters: [
    // ここからひらがな
    {
      text: "あ",
      unicode: "\u3042",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "い",
      unicode: "\u3044",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "う",
      unicode: "\u3046",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "え",
      unicode: "\u3048",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "お",
      unicode: "\u304A",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "か",
      unicode: "\u304B",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "き",
      unicode: "\u304D",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "く",
      unicode: "\u304F",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "け",
      unicode: "\u3051",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "こ",
      unicode: "\u3053",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "さ",
      unicode: "\u3055",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "し",
      unicode: "\u3057",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "す",
      unicode: "\u3059",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "せ",
      unicode: "\u305B",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "そ",
      unicode: "\u305D",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "た",
      unicode: "\u305F",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ち",
      unicode: "\u3061",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "つ",
      unicode: "\u3064",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "て",
      unicode: "\u3066",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "と",
      unicode: "\u3068",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "な",
      unicode: "\u306A",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "に",
      unicode: "\u306B",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぬ",
      unicode: "\u306C",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ね",
      unicode: "\u306D",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "の",
      unicode: "\u306E",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "は",
      unicode: "\u306F",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ひ",
      unicode: "\u3072",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ふ",
      unicode: "\u3075",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "へ",
      unicode: "\u3078",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ほ",
      unicode: "\u307B",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ま",
      unicode: "\u307E",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "み",
      unicode: "\u307F",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "む",
      unicode: "\u3080",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "め",
      unicode: "\u3081",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "も",
      unicode: "\u3082",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "や",
      unicode: "\u3084",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ゆ",
      unicode: "\u3086",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "よ",
      unicode: "\u3088",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ら",
      unicode: "\u3089",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "り",
      unicode: "\u308A",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "る",
      unicode: "\u308B",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "れ",
      unicode: "\u308C",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ろ",
      unicode: "\u308D",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "わ",
      unicode: "\u308F",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "を",
      unicode: "\u3092",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ん",
      unicode: "\u3093",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    // 濁音
    {
      text: "が",
      unicode: "\u304C",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぎ",
      unicode: "\u304E",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぐ",
      unicode: "\u3050",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "げ",
      unicode: "\u3052",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ご",
      unicode: "\u3054",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ざ",
      unicode: "\u3056",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "じ",
      unicode: "\u3058",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ず",
      unicode: "\u305A",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぜ",
      unicode: "\u305C",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぞ",
      unicode: "\u305E",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "だ",
      unicode: "\u3060",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぢ",
      unicode: "\u3062",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "づ",
      unicode: "\u3065",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "で",
      unicode: "\u3067",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ど",
      unicode: "\u3069",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ば",
      unicode: "\u3070",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "び",
      unicode: "\u3073",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぶ",
      unicode: "\u3076",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "べ",
      unicode: "\u3079",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぼ",
      unicode: "\u307C",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    // 半濁音
    {
      text: "ぱ",
      unicode: "\u3071",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぴ",
      unicode: "\u3074",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぷ",
      unicode: "\u3077",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぺ",
      unicode: "\u307A",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ぽ",
      unicode: "\u307D",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    // 拗音
    {
      text: "ゃ",
      unicode: "\u3083",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ゅ",
      unicode: "\u3085",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    {
      text: "ょ",
      unicode: "\u3087",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    // 促音
    {
      text: "っ",
      unicode: "\u3063",
      vector: "both",
      art: "NotCreated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
    },
    // ここまでひらがな
    // ここからカタカナ
    // 清音
    {
      text: "ア",
      unicode: "\u30a2",
      vector: "both",
      art: "┏━━━━┓\n┗━━━┓┃\n　　┏┓┃┃\n　　┃┃┗┛\n　┏┛┛　　\n　┗┛　　　\n",
    },
    {
      text: "イ",
      unicode: "\u30a4",
      vector: "both",
      art: "　　　　┏┓\n┏━━━┛┃\n┗━┓┏━┛\n　　┃┃　　\n　　┃┃　　\n　　┗┛　　\n",
    },
    {
      text: "ウ",
      unicode: "\u30a6",
      vector: "both",
      art: "　　┏┓　　\n┏━┛┗━┓\n┃┏━━┓┃\n┗┛　　┃┃\n　　　┏┛┃\n　　　┗━┛\n　\n",
    },
    {
      text: "エ",
      unicode: "\u30a8",
      vector: "both",
      art: "┏━━━━┓\n┗━┓┏━┛\n　　┃┃　　\n　　┃┃　　\n┏━┛┗━┓\n┗━━━━┛\n",
    },
    {
      text: "オ",
      unicode: "\u30aa",
      vector: "both",
      art: "　　　┏┓　\n┏━━┛┗┓\n┗━┓　┏┛\n　┏┛┃┃　\n┏┛┛┃┃　\n┗┛　┗┛　\n",
    },
    {
      text: "カ",
      unicode: "\u30ab",
      vector: "both",
      art: "　┏┓　　　\n┏┛┗━━┓\n┗┓┏━┓┃\n　┃┃　┃┃\n┏┛┛┏┛┃\n┗┛　┗━┛\n",
    },
    {
      text: "キ",
      unicode: "\u30ad",
      vector: "both",
      art: "　　┏┓　　\n┏━┛┗━┓\n┗━┓┏━┛\n┏━┛┗━┓\n┗━┓┏━┛\n　　┗┛　　\n",
    },
    {
      text: "ク",
      unicode: "\u30af",
      vector: "both",
      art: "┏┓　　　\n┃┗━━┓\n┃┏━┓┃\n┗┛　┃┃\n　　┏┛┃\n　　┗━┛\n",
    },
    {
      text: "ケ",
      unicode: "\u30b1",
      vector: "both",
      art: "┏┓　　　　　\n┃┗━━━┓　\n┃┏━┓┏┛　\n┗┛　┃┃　　\n　　　┃┃　　\n　　　┗┛　　\n",
    },
    {
      text: "コ",
      unicode: "\u30b3",
      vector: "both",
      art: "　　　　　　\n┏━━━━┓\n┗━━━┓┃\n　　　　┃┃\n┏━━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "サ",
      unicode: "\u30b5",
      vector: "both",
      art: "　┏┓┏┓　\n┏┛┗┛┗┓\n┗┓┏┓┏┛\n　┃┃┃┃　\n　┗┛┃┃　\n　　　┗┛　\n",
    },
    {
      text: "シ",
      unicode: "\u30b7",
      vector: "both",
      art: "　　　　┏┓\n┏━━┓┃┃\n┣━━┫┃┃\n┗━━┛┃┃\n┏━━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "ス",
      unicode: "\u30b9",
      vector: "both",
      art: "　　　　　　\n┏━━━━┓\n┗━━┓　┃\n　　／　／　\n　／／＼＼　\n┗┛　　┗┛\n",
    },
    {
      text: "セ",
      unicode: "\u30bb",
      vector: "both",
      art: "　┏┓　　　\n┏┛┗━━┓\n┗┓┏━┓┃\n　┃┃　┗┛\n　┃┗━━┓\n　┗━━━┛\n",
    },
    {
      text: "ソ",
      unicode: "\u30bd",
      vector: "both",
      art: "┏┓　　┏┓\n┗┗┓　┃┃\n　┗┛　┃┃\n　　　┏┛┛\n　┏━┛┛　\n　┗━┛　　\n",
    },
    {
      text: "タ",
      unicode: "\u30bf",
      vector: "both",
      art: "┏━━━━┓\n┃┏━━┓┃\n┃┃┏━┛┃\n┗┛┗━┓┃\n　　　┏┛┃\n　　　┗━┛\n",
    },
    {
      text: "チ",
      unicode: "\u30c1",
      vector: "both",
      art: "　┏━━┓　\n　┗┓┏┛　\n┏━┛┗━┓\n┗━┓┏━┛\n　┏┛┛　　\n　┗┛　　　\n",
    },
    {
      text: "ツ",
      unicode: "\u30c4",
      vector: "both",
      art: "┏┓┏┓┏┓\n┃┃┃┃┃┃\n┃┃┃┃┃┃\n┗┛┗┛┃┃\n┏━━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "テ",
      unicode: "\u30c6",
      vector: "both",
      art: "　┏━━┓　\n　┗━━┛　\n┏━━━━┓\n┗━┓┏━┛\n　┏┛┛　　\n　┗┛　　　\n",
    },
    {
      text: "ト",
      unicode: "\u30c8",
      vector: "both",
      art: "　┏━┓　　\n　┃　┃　　\n　┃　┗━┓\n　┃　┏━┛\n　┃　┃　　\n　┗━┛　　\n",
    },
    {
      text: "ナ",
      unicode: "\u30ca",
      vector: "both",
      art: "　　┏┓　　\n┏━┛┗━┓\n┗━┓┏━┛\n　　┃┃　　\n　┏┛┛　　\n　┗┛　　　\n",
    },
    {
      text: "ニ",
      unicode: "\u30cb",
      vector: "both",
      art: "　　　　　　\n　┏━━┓　\n　┗━━┛　\n　　　　　　\n┏━━━━┓\n┗━━━━┛\n",
    },
    {
      text: "ヌ",
      unicode: "\u30cc",
      vector: "both",
      art: "┏━━━━┓\n┗━━┓　┃\n　┏━┛┏┛\n　┗┳　┗┓\n┏━┛┗┓┃\n┗━┛　┗┛\n",
    },
    {
      text: "ネ",
      unicode: "\u30cd",
      vector: "both",
      art: "　　┏┓　　\n┏━┛┗━┓\n┗━━┓┏┛\n　┏┛┏╋┓\n┏┛┫┃┗┛\n┗┛┗┛　　\n",
    },
    {
      text: "ノ",
      unicode: "\u30ce",
      vector: "both",
      art: "　　┏┓　　\n　　┃┃　　\n　　┃┃　　\n　┏┛┛　　\n┏┛┛　　　\n┗┛　　　　\n",
    },
    {
      text: "ハ",
      unicode: "\u30cf",
      vector: "both",
      art: "　┏┓┏┓　\n　┃┃┃┃　\n　┃┃┃┃　\n　┃┃┃┗┓\n┏┛┛┗┓┃\n┗┛　　┗┛\n",
    },
    {
      text: "ヒ",
      unicode: "\u30d2",
      vector: "both",
      art: "┏┓　　　　\n┃┃　　　　\n┃┗━━━┓\n┃┏━━━┛\n┃┗━━━┓\n┗━━━━┛\n",
    },
    {
      text: "フ",
      unicode: "\u30d5",
      vector: "both",
      art: "┏━━━━┓\n┗━━━┓┃\n　　　┏┛┛\n　　┏┛┛　\n　┏┛┛　　\n　┗┛　　　\n",
    },
    {
      text: "ヘ",
      unicode: "\u30d8",
      vector: "both",
      art: "　　　　　　\n　┏━┓　　\n┏┛━┗┓　\n┃┃　┗┗┓\n┗┛　　┃┃\n　　　　┗┛\n",
    },
    {
      text: "ホ",
      unicode: "\u30db",
      vector: "both",
      art: "　　┏┓　　\n┏━┛┗━┓\n┗━┓┏━┛\n┏┓┃┃┏┓\n┃┃┃┃┃┃\n┗┛┗┛┗┛\n",
    },
    {
      text: "マ",
      unicode: "\u30de",
      vector: "both",
      art: "┏━━━━┓\n┗━━━┓┃\n　━　　┃┃\n　＼＼／／　\n　　＼＼　　\n　　　━　　\n",
    },
    {
      text: "ミ",
      unicode: "\u30df",
      vector: "both",
      art: "┏━━━━┓\n┗━━━━┛\n┏━━━━┓\n┗━━━━┛\n┏━━━━┓\n┗━━━━┛\n",
    },
    {
      text: "ム",
      unicode: "\u30e0",
      vector: "both",
      art: "┏┓　　　　\n┃┃　　　　\n┃┃　　┏┓\n┃┗━━┛┃\n┗━━━┓┃\n　　　　┗┛\n",
    },
    {
      text: "メ",
      unicode: "\u30e1",
      vector: "both",
      art: "　　　　　▁\n　▁　　／／\n　＼＼／／　\n　／／＼＼　\n／／　　▔　\n▔　　　　　\n",
    },
    {
      text: "モ",
      unicode: "\u30e2",
      vector: "both",
      art: "┏━━━━┓\n┗━┓┏━┛\n┏━┛┗━┓\n┗━┓┏━┛\n　　┃┗━┓\n　　┗━━┛\n",
    },
    {
      text: "ヤ",
      unicode: "\u30e4",
      vector: "both",
      art: "　┏┓　　　\n┏┛┗━━┓\n┗┓┏━┓┃\n　┃┃　┗┛\n　┃┃　　　\n　┗┛　　　\n",
    },
    {
      text: "ユ",
      unicode: "\u30e6",
      vector: "both",
      art: "　┏━━┓　\n　┗━┓┃　\n　　　┃┃　\n　　　┃┃　\n┏━━┛┗┓\n┗━━━━┛\n",
    },
    {
      text: "ヨ",
      unicode: "\u30e8",
      vector: "both",
      art: "┏━━━━┓\n┗━━━┓┃\n┏━━━┛┃\n┗━━━┓┃\n┏━━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "ラ",
      unicode: "\u30e9",
      vector: "both",
      art: "　┏━━┓　\n　┗━━┛　\n┏━━━━┓\n┗━━━┓┃\n　┏━━┛┛\n　┗━━┛　\n",
    },
    {
      text: "リ",
      unicode: "\u30ea",
      vector: "both",
      art: "　┏┓┏┓\n　┃┃┃┃\n　┃┃┃┃\n　┗┛┃┃\n　┏━┛┃\n　┗━━┛\n",
    },
    {
      text: "ル",
      unicode: "\u30eb",
      vector: "both",
      art: "　　　┏┓　　\n　┏┓┃┃　　\n　┃┃┃┃　　\n　┃┃┃┃　　\n┏┛┛┃┗┓　\n┗┛　┗━┛　\n",
    },
    {
      text: "レ",
      unicode: "\u30ec",
      vector: "both",
      art: "┏┓　　　　\n┃┃　　　　\n┃┃　　┏┓\n┃┃　┏┏┛\n┃┗━┏┛　\n┗━━┛　　\n",
    },
    {
      text: "ロ",
      unicode: "\u30ed",
      vector: "both",
      art: "　　　　　　\n┏━━━━┓\n┃┏━━┓┃\n┃┃　　┃┃\n┃┗━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "ワ",
      unicode: "\u30ef",
      vector: "both",
      art: "┏━━━━┓\n┃┏━━┓┃\n┗┛　　┃┃\n　　　　┃┃\n　　　┏┛┃\n　　　┗━┛\n",
    },
    {
      text: "ヲ",
      unicode: "\u30f2",
      vector: "both",
      art: "┏━━━━┓\n┗━━━┓┃\n┏━━━┛┃\n┗━━━┓┃\n　　┏━┛┛\n　　┗━┛　\n",
    },
    {
      text: "ン",
      unicode: "\u30f3",
      vector: "both",
      art: "　　　　　\n┏━┓┏┓\n┗━┛┃┃\n　　　┃┃\n┏━━┛┃\n┗━━━┛\n",
    },
    // 濁音
    {
      text: "ガ",
      unicode: "\u30ac",
      vector: "both",
      art: "　┏┓┏┳┓\n┏┛┗┗┻┫\n┗┓┏━┓┃\n　┃┃　┃┃\n┏┛┛┏┛┃\n┗┛　┗━┛\n",
    },
    {
      text: "ギ",
      unicode: "\u30ae",
      vector: "both",
      art: "　　┏┳┳┓\n┏━┛┗┻┫\n┗━┓┏━┛\n┏━┛┗━┓\n┗━┓┏━┛\n　　┗┛　　\n",
    },
    {
      text: "グ",
      unicode: "\u30b0",
      vector: "both",
      art: "┏┓　┏┳┓\n┃┗━┗╋┛\n┃┏━┓┃　\n┗┛　┃┃　\n　　┏┛┃　\n　　┗━┛　\n",
    },
    {
      text: "ゲ",
      unicode: "\u30b2",
      vector: "both",
      art: "┏┓　┏┳┓\n┃┗━┗┻┫\n┃┏━┓┏┛\n┗┛　┃┃　\n　　　┃┃　\n　　　┗┛　\n",
    },
    {
      text: "ゴ",
      unicode: "\u30b4",
      vector: "both",
      art: "　　　┏┳┓\n┏━━┗┻┫\n┗━━━┓┃\n　　　　┃┃\n┏━━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "ザ",
      unicode: "\u30b6",
      vector: "both",
      art: "　　　┏┳┓\n　┏┓┣╋┛\n┏┛┗┛┗┓\n┗┓┏┓┏┛\n　┗┛┃┃　\n　　　┗┛　\n",
    },
    {
      text: "ジ",
      unicode: "\u30b8",
      vector: "both",
      art: "　　　┏┳┓\n┏━━┗┻┫\n┣━━┫┃┃\n┗━━┛┃┃\n┏━━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "ズ",
      unicode: "\u30ba",
      vector: "both",
      art: "　　　┏┳┓\n┏━━┻┻┫\n┗━━┓　┃\n　　／　／　\n　／／＼＼　\n┗┛　　┗┛\n",
    },
    {
      text: "ゼ",
      unicode: "\u30bc",
      vector: "both",
      art: "　┏┓┏┳┓\n┏┛┗┗┻┫\n┗┓┏━┓┃\n　┃┃　┗┛\n　┃┗━━┓\n　┗━━━┛\n",
    },
    {
      text: "ゾ",
      unicode: "\u30be",
      vector: "both",
      art: "┏┓　┏┳┓\n┗┗┓┗┻┫\n　┗┛　┃┃\n　　　┏┛┛\n　┏━┛┛　\n　┗━┛　　\n",
    },
    {
      text: "ダ",
      unicode: "\u30c0",
      vector: "both",
      art: "┏━━┏┳┓\n┃┏━━┻┫\n┃┃┏━┛┃\n┗┛┗━┓┃\n　　　┏┛┃\n　　　┗━┛\n",
    },
    {
      text: "ヂ",
      unicode: "\u30c2",
      vector: "both",
      art: "　┏━┏┳┓　\n　┗┓┗┻┛\n┏━┛┗━┓\n┗━┓┏━┛\n　┏┛┛　　\n　┗┛　　　\n",
    },
    {
      text: "ヅ",
      unicode: "\u30c5",
      vector: "both",
      art: "　　　┏┳┓\n┏┓┏┗┻┫\n┃┃┃┃┃┃\n┗┛┗┛┃┃\n┏━━━┛┃\n┗━━━━┛\n",
    },
    {
      text: "デ",
      unicode: "\u30c7",
      vector: "both",
      art: "　┏━┏┳┓\n　┗━┗┻┛\n┏━━━━┓\n┗━┓┏━┛\n　┏┛┛　　\n　┗┛　　　\n",
    },
    {
      text: "ド",
      unicode: "\u30c9",
      vector: "both",
      art: "　┏━┳┳┓\n　┃　┣┻┛\n　┃　┗━┓\n　┃　┏━┛\n　┃　┃　　\n　┗━┛　　\n",
    },
    {
      text: "バ",
      unicode: "\u30D0",
      vector: "both",
      art: "　　　┏┳┓\n　┏┓┣╋┛\n　┃┃┃┃　\n　┃┃┃┗┓\n┏┛┛┗┓┃\n┗┛　　┗┛\n",
    },
    {
      text: "ビ",
      unicode: "\u30D3",
      vector: "both",
      art: "　　　┏┳┓\n┏┓　┗┻┛\n┃┗━━━┓\n┃┏━━━┛\n┃┗━━━┓\n┗━━━━┛\n",
    },
    {
      text: "ブ",
      unicode: "\u30D6",
      vector: "both",
      art: "　　　┏┳┓\n┏━━┻┻┫\n┗━━━┓┃\n　　　┏┛┛\n　　┏┛┛　\n　　┗┛　　\n",
    },
    {
      text: "ベ",
      unicode: "\u30D9",
      vector: "both",
      art: "　　　┏┳┓\n　┏━╋┻┛\n┏┛━┗┓　\n┃┃　┗┗┓\n┗┛　　┃┃\n　　　　┗┛\n",
    },
    {
      text: "ボ",
      unicode: "\u30DC",
      vector: "both",
      art: "　　┏┳┳┓\n┏━┛┗┻┫\n┗━┓┏━┛\n┏┓┃┃┏┓\n┃┃┃┃┃┃\n┗┛┗┛┗┛\n",
    },
    // 半濁音
    {
      text: "パ",
      unicode: "\u30D1",
      vector: "both",
      art: "　　　　┏┓\n　┏┓┏┗┛\n　┃┃┃┃　\n　┃┃┃┗┓\n┏┛┛┗┓┃\n┗┛　　┗┛\n",
    },
    {
      text: "ピ",
      unicode: "\u30D4",
      vector: "both",
      art: "┏┓　　┏┓\n┃┃　　┗┛\n┃┗━━━┓\n┃┏━━━┛\n┃┗━━━┓\n┗━━━━┛\n",
    },
    {
      text: "プ",
      unicode: "\u30D7",
      vector: "both",
      art: "　　　　┏┓\n┏━━━┗┛\n┗━━━┓┃\n　　　┏┛┛\n　　┏┛┛　\n　　┗┛　　　\n",
    },
    {
      text: "ペ",
      unicode: "\u30DA",
      vector: "both",
      art: "　　　　┏┓\n　┏━┓┗┛\n┏┛━┗┓　\n┃┃　┗┗┓\n┗┛　　┃┃\n　　　　┗┛\n",
    },
    {
      text: "ポ",
      unicode: "\u30DD",
      vector: "both",
      art: "　　┏┓┏┓\n┏━┛┗┗┛\n┗━┓┏━┛\n┏┓┃┃┏┓\n┃┃┃┃┃┃\n┗┛┗┛┗┛\n",
    },
    // 小文字
    {
      text: "ァ",
      unicode: "\u30a1",
      vector: "both",
      art: "　　　　　　\n　┏━━━┓\n　┗━━┓┃\n　　┏┓┗┛\n　　┃┃　　\n　　┗┛　　\n",
    },
    {
      text: "ィ",
      unicode: "\u30a3",
      vector: "both",
      art: "　　　　\n　　┏┓\n┏━┛┃\n┗┓┏┛\n    ┃┃   \n    ┗┛   \n",
    },
    {
      text: "ェ",
      unicode: "\u30a7",
      vector: "both",
      art: "　　　　　\n　　　　　\n　┏━━┓\n　┗┓┏┛\n　┏┛┗┓\n　┗━━┛\n",
    },
    // 拗音
    {
      text: "ャ",
      unicode: "\u30e3",
      vector: "both",
      art: "　　　　　　\n　　┏┓　　\n　┏┛┗━┓\n　┗┓┏┓┃\n　　┃┃┗┛\n　　┗┛　　\n",
    },
    {
      text: "ュ",
      unicode: "\u30e5",
      vector: "both",
      art: "　　　　　　\n　　┏━┓　\n　　┗┓┃　\n　　┏┛┗┓\n　　┗━━┛\n",
    },
    {
      text: "ョ",
      unicode: "\u30e7",
      vector: "both",
      art: "　　　　　　\n　　┏━━┓\n　　┣━　┃\n　　┣━　┃\n　　┗━━┛\n",
    },
    // 促音
    {
      text: "ッ",
      unicode: "\u30C3",
      vector: "both",
      art: "　　　　　　\n　　　　　　\n　┏┳┓┏┓\n　┗┻┛┃┃\n　┏━━┛┃\n　┗━━━┛\n",
    },
    // ここからアルファベット
    {
      text: "A",
      unicode: "\u0041",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┗┛┃\n┃┏┓┃\n┃┃┃┃\n┗┛┗┛\n",
    },
    {
      text: "B",
      unicode: "\u0042",
      vector: "both",
      art: "┏━＼　\n┃┏┓┃\n┃┗┛／\n┃┏┓＼\n┃┗┛┃\n┗━／　\n",
    },
    {
      text: "C",
      unicode: "\u0043",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┃　　\n┃┃　　\n┃┗━┓\n┗━━┛\n",
    },
    {
      text: "D",
      unicode: "\u0044",
      vector: "both",
      art: "┏━＼　　\n┃┏＼＼　\n┃┃　┃┃\n┃┃　┃┃\n┃┗／／　\n┗━／　　\n",
    },
    {
      text: "E",
      unicode: "\u0045",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┗━┓\n┃┏━┛\n┃┗━┓\n┗━━┛\n",
    },
    {
      text: "F",
      unicode: "\u0046",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┗━┓\n┃┏━┛\n┃┃　　\n┗┛　　\n",
    },
    {
      text: "G",
      unicode: "\u0047",
      vector: "both",
      art: "┏━━┓　\n┃┏━┛　\n┃┣━━┓\n┃┣┓┏┛\n┃┗┛┃　\n┗━━┛　\n",
    },
    {
      text: "H",
      unicode: "\u0048",
      vector: "both",
      art: "┏┓┏┓\n┃┃┃┃\n┃┗┛┃\n┃┏┓┃\n┃┃┃┃\n┗┛┗┛\n",
    },
    {
      text: "I",
      unicode: "\u0049",
      vector: "both",
      art: "┏━━┓\n┗┓┏┛\n　┃┃　\n　┃┃　\n┏┛┗┓\n┗━━┛\n",
    },
    {
      text: "J",
      unicode: "\u004A",
      vector: "both",
      art: "┏━━┓\n┗┓┏┛\n　┃┃　\n　┃┃　\n┏┛┃　\n┗━┛　\n",
    },
    {
      text: "K",
      unicode: "\u004B",
      vector: "both",
      art: "┏┓┏┓\n┃┃┃┃\n┃┗┛┃\n┃┏┓┛\n┃┃┃┓\n┗┛┗┛\n",
    },
    {
      text: "L",
      unicode: "\u004C",
      vector: "both",
      art: "┏┓　　\n┃┃　　\n┃┃　　\n┃┃　　\n┃┗━┓\n┗━━┛\n",
    },
    {
      text: "M",
      unicode: "\u004D",
      vector: "both",
      art: "┏━━━━┓\n┃┏┓┏┓┃\n┃┃┃┃┃┃\n┃┃┃┃┃┃\n┃┃┃┃┃┃\n┗┛┗┛┗┛\n",
    },
    {
      text: "N",
      unicode: "\u004E",
      vector: "both",
      art: "┏┓┏┓\n┃┗┓┃\n┃　　┃\n┃┗┓┃\n┃┃┃┃\n┗┛┗┛\n",
    },
    {
      text: "O",
      unicode: "\u004F",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┃┃┃\n┃┃┃┃\n┃┗┛┃\n┗━━┛\n",
    },
    {
      text: "P",
      unicode: "\u0050",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┗┛┃\n┃┏━┛\n┃┃　　\n┗┛　　\n",
    },
    {
      text: "Q",
      unicode: "\u0051",
      vector: "both",
      art: "┏━━┓　\n┃┏┓┃　\n┃┃┃┃　\n┃┣┛┗┓\n┃┗　┏┛\n┗━━┛　\n",
    },
    {
      text: "R",
      unicode: "\u0052",
      vector: "both",
      art: "┏━━━┓\n┃┏━┓┃\n┃┗━┛┃\n┃┏┓┏┛\n┃┃┃┃　\n┗┛┗┛　\n",
    },
    {
      text: "S",
      unicode: "\u0053",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┗━┓\n┗━┓┃\n┏━┛┃\n┗━━┛\n",
    },
    {
      text: "T",
      unicode: "\u0054",
      vector: "both",
      art: "┏━━┓\n┗┓┏┛\n　┃┃　\n　┃┃　\n　┃┃　\n　┗┛　\n",
    },
    {
      text: "U",
      unicode: "\u0055",
      vector: "both",
      art: "┏┓┏┓\n┃┃┃┃\n┃┃┃┃\n┃┃┃┃\n┃┗┛┃\n┗━━┛\n",
    },
    {
      text: "V",
      unicode: "\u0056",
      vector: "both",
      art: "┏┓┏┓　\n┃┃┃┃　\n┃┃┃┃　\n \\ ┃┃ /　 \n  \\┗┛/　  \n　▔▔　　\n",
    },
    {
      text: "W",
      unicode: "\u0057",
      vector: "both",
      art: "┏┓┏┓┏┓\n┃┃┃┃┃┃\n┃┃┃┃┃┃\n┃┃┃┃┃┃\n┃┗┛┗┛┃\n┗━━━━┛\n",
    },
    {
      text: "X",
      unicode: "\u0058",
      vector: "both",
      art: "▁　　　　▁\n＼＼　　／／\n　＼＼／／　\n　／／＼＼　\n／／　　＼＼\n▔　　　　▔\n",
    },
    {
      text: "Y",
      unicode: "\u0059",
      vector: "both",
      art: "┏┓┏┓\n┃┃┃┃\n┃┗┛┃\n┗┓┏┛\n　┃┃　\n　┗┛　\n",
    },
    {
      text: "Z",
      unicode: "\u005A",
      vector: "both",
      art: "┏━━━┓\n┗━━／／\n　　／／　\n　／／　　\n／／━━┓\n┗━━━┛\n",
    },
    // ここまでアルファベット
    // ここから記号
    {
      text: "-",
      unicode: "\u002d",
      vector: "horizon",
      art: "　　　　\n　　　　\n┏━━┓\n┗━━┛\n　　　　\n　　　　\n",
    },
    {
      text: "ー",
      unicode: "\u30fc",
      vector: "horizon",
      art: "　　　　\n　　　　\n┏━━┓\n┗━━┛\n　　　　\n　　　　\n",
    },
    {
      text: "ー",
      unicode: "\u30fc",
      vector: "vertical",
      art: "　┏┓　　\n　┃┃　　\n　┃┃　　\n　┃┃　　\n　┃┃　　\n　┗┛　　\n",
    },
    {
      text: "!",
      unicode: "\u0021",
      vector: "both",
      art: "　　┏┓　　\n　　┃┃　　\n　　┃┃　　\n　　┗┛　　\n　　┏┓　　\n　　┗┛　　\n",
    },
    {
      text: "！",
      unicode: "\uff01",
      vector: "both",
      art: "　　┏┓　　\n　　┃┃　　\n　　┃┃　　\n　　┗┛　　\n　　┏┓　　\n　　┗┛　　\n",
    },
    {
      text: "?",
      unicode: "\u003F",
      vector: "both",
      art: "　　┏┓　　\n　　┃┃　　\n　　┃┃　　\n　　┃┃　　\n　　┗┛　　\n",
    },
    {
      text: "？",
      unicode: "\uff1f",
      vector: "both",
      art: "　　┏┓　　\n　　┃┃　　\n　　┃┃　　\n　　┃┃　　\n　　┗┛　　\n",
    },
    {
      text: "(",
      unicode: "\u0028",
      vector: "both",
      art: "　　┏┓　\n　／／　　\n┃┃　　　\n┃┃　　　\n　＼＼　　\n　　┗┛　\n",
    },
    {
      text: ")",
      unicode: "\u0029",
      vector: "both",
      art: "┏┓　　　\n　＼＼　　\n　　┃┃　\n　　┃┃　\n　／／　　\n┗┛　　　\n",
    },
    {
      text: "（",
      unicode: "\uFF08",
      vector: "both",
      art: "　　┏┓　\n　／／　　\n┃┃　　　\n┃┃　　　\n　＼＼　　\n　　┗┛　\n",
    },
    {
      text: "）",
      unicode: "\uFF09",
      vector: "both",
      art: "┏┓　　　\n　＼＼　　\n　　┃┃　\n　　┃┃　\n　／／　　\n┗┛　　　\n",
    },
    {
      text: "!",
      unicode: "\u0021",
      vector: "both",
      art: "　┏┓　\n　┃┃　\n　┃┃　\n　┗┛　\n　┏┓　\n　┗┛　\n",
    },
    {
      text: "！",
      unicode: "\uff01",
      vector: "both",
      art: "　┏┓　\n　┃┃　\n　┃┃　\n　┗┛　\n　┏┓　\n　┗┛　\n",
    },
    {
      text: "?",
      unicode: "\u003F",
      vector: "both",
      art: "　　┏┓　　\n　　┃┃　　\n　　┃┃　　\n　　┃┃　　\n　　┗┛　　\n",
    },
    {
      text: "？",
      unicode: "\uff1f",
      vector: "both",
      art: "　　┏┓　　\n　　┃┃　　\n　　┃┃　　\n　　┃┃　　\n　　┗┛　　\n",
    },
    {
      text: "(",
      unicode: "\u0028",
      vector: "both",
      art: "　　┏┓　\n　／／　　\n┃┃　　　\n┃┃　　　\n　＼＼　　\n　　┗┛　\n",
    },
    {
      text: ")",
      unicode: "\u0029",
      vector: "both",
      art: "┏┓　　　\n　＼＼　　\n　　┃┃　\n　　┃┃　\n　／／　　\n┗┛　　　\n",
    },
    {
      text: "（",
      unicode: "\uFF08",
      vector: "both",
      art: "　　┏┓　\n　／／　　\n┃┃　　　\n┃┃　　　\n　＼＼　　\n　　┗┛　\n",
    },
    {
      text: "）",
      unicode: "\uFF09",
      vector: "both",
      art: "┏┓　　　\n　＼＼　　\n　　┃┃　\n　　┃┃　\n　／／　　\n┗┛　　　\n",
    },
    {
      text: "♡",
      unicode: "\u2661",
      vector: "both",
      art: "　　＿　　＿　　\n　／　＼／　＼　\n（　　　　　　）\n　＼　　　　／　\n　　＼　　／　　\n　　　＼／　　　\n",
    },
    {
      text: "・",
      unicode: "\u30FB",
      vector: "both",
      art: "　　　　　　\n　　　　　　\n　　┏━┓　\n　　┃　┃　\n　　┗━┛　\n 　　　　　　\n",
    },
    {
      text: ":",
      unicode: "\u003A",
      vector: "both",
      art: "┏┓\n┃┃\n┗┛\n┏┓\n┃┃\n┗┛\n",
    },
    {
      text: "：",
      unicode: "\uFF1A",
      vector: "both",
      art: "┏┓\n┃┃\n┗┛\n┏┓\n┃┃\n┗┛\n",
    },
    {
      text: "0",
      unicode: "\u0030",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┃┃┃\n┃┃┃┃\n┃┗┛┃\n┗━━┛\n",
    },
    {
      text: "０",
      unicode: "\uFF10",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┃┃┃\n┃┃┃┃\n┃┗┛┃\n┗━━┛\n",
    },
    // ここまで記号
    // ここから数字
    {
      text: "1",
      unicode: "\u0031",
      vector: "both",
      art: "┏━┓　\n┗┓┃　\n　┃┃　\n　┃┃　\n┏┛┗┓\n┗━━┛\n",
    },
    {
      text: "１",
      unicode: "\uFF11",
      vector: "both",
      art: "┏━┓　\n┗┓┃　\n　┃┃　\n　┃┃　\n┏┛┗┓\n┗━━┛\n",
    },
    {
      text: "2",
      unicode: "\u0032",
      vector: "both",
      art: "┏━━┓\n┗━┓┃\n┏━┛┃\n┃┏━┛\n┃┗━┓\n┗━━┛\n",
    },
    {
      text: "２",
      unicode: "\uFF12",
      vector: "both",
      art: "┏━━┓\n┗━┓┃\n┏━┛┃\n┃┏━┛\n┃┗━┓\n┗━━┛\n",
    },
    {
      text: "3",
      unicode: "\u0033 ",
      vector: "both",
      art: "┏━━┓\n┗━┓┃\n┏━┛┃\n┗━┓┃\n┏━┛┃\n┗━━┛\n",
    },
    {
      text: "３",
      unicode: "\uFF13",
      vector: "both",
      art: "┏━━┓\n┗━┓┃\n┏━┛┃\n┗━┓┃\n┏━┛┃\n┗━━┛\n",
    },
    {
      text: "4",
      unicode: "\u0034 ",
      vector: "both",
      art: "┏┓┏┓\n┃┃┃┃\n┃┗┛┃\n┗━┓┃\n　　┃┃\n　　┗┛\n",
    },
    {
      text: "４",
      unicode: "\uFF14",
      vector: "both",
      art: "┏┓┏┓\n┃┃┃┃\n┃┗┛┃\n┗━┓┃\n　　┃┃\n　　┗┛\n",
    },
    {
      text: "5",
      unicode: "\u0035 ",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┗━┓\n┗━┓┃\n┏━┛┃\n┗━━┛\n",
    },
    {
      text: "５",
      unicode: "\uFF15",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┗━┓\n┗━┓┃\n┏━┛┃\n┗━━┛\n",
    },
    {
      text: "6",
      unicode: "\u0036",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┗━┓\n┃┏┓┃\n┃┗┛┃\n┗━━┛\n",
    },
    {
      text: "６",
      unicode: "\uFF16",
      vector: "both",
      art: "┏━━┓\n┃┏━┛\n┃┗━┓\n┃┏┓┃\n┃┗┛┃\n┗━━┛\n",
    },
    {
      text: "7",
      unicode: "\u0037",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┗┛┃┃\n　　┃┃\n　　┃┃\n　　┗┛\n",
    },
    {
      text: "７",
      unicode: "\uFF17",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┗┛┃┃\n　　┃┃\n　　┃┃\n　　┗┛\n",
    },
    {
      text: "8",
      unicode: "\u0038",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┗┛┃\n┃┏┓┃\n┃┗┛┃\n┗━━┛\n",
    },
    {
      text: "８",
      unicode: "\uFF18",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┗┛┃\n┃┏┓┃\n┃┗┛┃\n┗━━┛\n",
    },
    {
      text: "9",
      unicode: "\u0039",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┗┛┃\n┗━┓┃\n┏━┛┃\n┗━━┛\n",
    },
    {
      text: "９",
      unicode: "\uFF19",
      vector: "both",
      art: "┏━━┓\n┃┏┓┃\n┃┗┛┃\n┗━┓┃\n┏━┛┃\n┗━━┛\n",
    },
  ],
};
