import { Lib } from "./definition";

export const data: Lib[] = [
  {
    kind: "Katakana",
    vector: "vertical",
    width: "half",
    letters: [
      // 清音
      {
        text: "ア",
        prounounce: "a",
        unicode: "\u30a2",
        art: "┌────┐\n└───┐│\n  ┌┐││\n  ││└┘\n ┌┘┘  \n └┘   \n",
      },
      {
        text: "イ",
        prounounce: "i",
        unicode: "\u30a4",
        art: "    ┌┐\n┌───┘│\n└─┐┌─┘\n  ││  \n  ││  \n  └┘  \n",
      },
      {
        text: "ウ",
        prounounce: "u",
        unicode: "\u30a6",
        art: "  ┌┐  \n┌─┘└─┐\n│┌──┐│\n└┘  ││\n   ┌┘│\n   └─┘\n \n",
      },
      {
        text: "エ",
        prounounce: "e",
        unicode: "\u30a8",
        art: "┌────┐\n└─┐┌─┘\n  ││  \n  ││  \n┌─┘└─┐\n└────┘\n",
      },
      {
        text: "オ",
        prounounce: "o",
        unicode: "\u30aa",
        art: "   ┌┐ \n┌──┘└┐\n└─┐ ┌┘\n ┌┘││ \n┌┘┘││ \n└┘ └┘ \n",
      },
      {
        text: "カ",
        prounounce: "ka",
        unicode: "\u30ab",
        art: " ┌┐   \n┌┘└──┐\n└┐┌─┐│\n ││ ││\n┌┘┘┌┘│\n└┘ └─┘\n",
      },
      {
        text: "キ",
        prounounce: "ki",
        unicode: "\u30ad",
        art: "  ┌┐  \n┌─┘└─┐\n└─┐┌─┘\n┌─┘└─┐\n└─┐┌─┘\n  └┘  \n",
      },
      {
        text: "ク",
        prounounce: "ku",
        unicode: "\u30af",
        art: "┌┐   \n│└──┐\n│┌─┐│\n└┘ ││\n  ┌┘│\n  └─┘\n",
      },
      {
        text: "ケ",
        prounounce: "ke",
        unicode: "\u30b1",
        art: "┌┐     \n│└───┐ \n│┌─┐┌┘ \n└┘ ││  \n   ││  \n   └┘  \n",
      },
      {
        text: "コ",
        prounounce: "ko",
        unicode: "\u30b3",
        // art: "┌────┐\n└───┐│\n    ││\n    ││\n┌───┘│\n└────┘\n",
        art: "      \n┌────┐\n└───┐│\n    ││\n┌───┘│\n└────┘\n",
      },
      {
        text: "サ",
        prounounce: "sa",
        unicode: "\u30b5",
        art: " ┌┐┌┐ \n┌┘└┘└┐\n└┐┌┐┌┘\n ││││ \n └┘││ \n   └┘ \n",
      },
      {
        text: "シ",
        prounounce: "shi",
        unicode: "\u30b7",
        art: "    ┌┐\n┌──┐││\n├──┤││\n└──┘││\n┌───┘│\n└────┘\n",
      },
      {
        text: "ス",
        prounounce: "su",
        unicode: "\u30b9",
        art: "┌────┐\n└──┐ │\n  ┌┘┌ \n ┌┘┬└┐\n┌┘┘└┐│\n└┘  └┘\n",
      },
      {
        text: "セ",
        prounounce: "se",
        unicode: "\u30bb",
        art: " ┌┐   \n┌┘└──┐\n└┐┌─┐│\n ││ └┘\n │└──┐\n └───┘\n",
      },
      {
        text: "ソ",
        prounounce: "so",
        unicode: "\u30bd",
        art: "┌┐  ┌┐\n└└┐ ││\n └┘ ││\n   ┌┘┘\n ┌─┘┘ \n └─┘  \n",
      },
      {
        text: "タ",
        prounounce: "ta",
        unicode: "\u30bf",
        art: "┌────┐\n│┌──┐│\n││┌─┘│\n└┘└─┐│\n   ┌┘│\n   └─┘\n",
      },
      {
        text: "チ",
        prounounce: "chi",
        unicode: "\u30c1",
        art: " ┌──┐ \n └┐┌┘ \n┌─┘└─┐\n└─┐┌─┘\n ┌┘┘  \n └┘   \n",
      },
      {
        text: "ツ",
        prounounce: "tsu",
        unicode: "\u30c4",
        art: "┌┐┌┐┌┐\n││││││\n││││││\n└┘└┘││\n┌───┘│\n└────┘\n",
      },
      {
        text: "テ",
        prounounce: "te",
        unicode: "\u30c6",
        art: " ┌──┐ \n └──┘ \n┌────┐\n└─┐┌─┘\n ┌┘┘  \n └┘   \n",
      },
      {
        text: "ト",
        prounounce: "to",
        unicode: "\u30c8",
        art: " ┌─┐  \n │ │  \n │ └─┐\n │ ┌─┘\n │ │  \n └─┘  \n",
      },
      {
        text: "ナ",
        prounounce: "na",
        unicode: "\u30ca",
        art: "  ┌┐  \n┌─┘└─┐\n└─┐┌─┘\n  ││  \n ┌┘┘  \n └┘   \n",
      },
      {
        text: "ニ",
        prounounce: "ni",
        unicode: "\u30cb",
        art: "      \n ┌──┐ \n └──┘ \n      \n┌────┐\n└────┘\n",
      },
      {
        text: "ヌ",
        prounounce: "nu",
        unicode: "\u30cc",
        art: "┌────┐\n└──┐ │\n ┌─┘┌┘\n └┬ └┐\n┌─┘└┐│\n└─┘ └┘\n",
      },
      {
        text: "ネ",
        prounounce: "ne",
        unicode: "\u30cd",
        art: "  ┌┐  \n┌─┘└─┐\n└──┐┌┘\n ┌┘┌┼┐\n┌┘┤│└┘\n└┘└┘  \n",
      },
      {
        text: "ノ",
        prounounce: "no",
        unicode: "\u30ce",
        art: "  ┌┐  \n  ││  \n  ││  \n ┌┘┘  \n┌┘┘   \n└┘    \n",
      },
      {
        text: "ハ",
        prounounce: "ha",
        unicode: "\u30cf",
        art: " ┌┐┌┐ \n ││││ \n ││││ \n │││└┐\n┌┘┘└┐│\n└┘  └┘\n",
      },
      {
        text: "ヒ",
        prounounce: "hi",
        unicode: "\u30d2",
        art: "┌┐    \n││    \n│└───┐\n│┌───┘\n│└───┐\n└────┘\n",
      },
      {
        text: "フ",
        prounounce: "fu",
        unicode: "\u30d5",
        art: "┌────┐\n└───┐│\n   ┌┘┘\n  ┌┘┘ \n ┌┘┘  \n └┘   \n",
      },
      {
        text: "ヘ",
        prounounce: "he",
        unicode: "\u30d8",
        art: "      \n ┌─┐  \n┌┘─└┐ \n││ └└┐\n└┘  ││\n    └┘\n",
      },
      {
        text: "ホ",
        prounounce: "ho",
        unicode: "\u30db",
        art: "  ┌┐  \n┌─┘└─┐\n└─┐┌─┘\n┌┐││┌┐\n││││││\n└┘└┘└┘\n",
      },
      {
        text: "マ",
        prounounce: "ma",
        unicode: "\u30de",
        art: "┌────┐\n└───┐│\n ┌┐ ││\n │└─┘│\n │┌──┘\n └┘   \n",
      },
      {
        text: "ミ",
        prounounce: "mi",
        unicode: "\u30df",
        art: "┌────┐\n└────┘\n┌────┐\n└────┘\n┌────┐\n└────┘\n",
      },
      {
        text: "ム",
        prounounce: "mu",
        unicode: "\u30e0",
        art: "┌┐    \n││    \n││  ┌┐\n│└──┘│\n└───┐│\n    └┘\n",
      },
      {
        text: "メ",
        prounounce: "me",
        unicode: "\u30e1",
        art: "      \n ┌┐ ┌┐\n └┐─┌┘\n ┌┘─└┐\n┌┘┘ └┘\n└┘    \n",
      },
      {
        text: "モ",
        prounounce: "mo",
        unicode: "\u30e2",
        art: "┌────┐\n└─┐┌─┘\n┌─┘└─┐\n└─┐┌─┘\n  │└─┐\n  └──┘\n",
      },
      {
        text: "ヤ",
        prounounce: "ya",
        unicode: "\u30e4",
        art: " ┌┐   \n┌┘└──┐\n└┐┌─┐│\n ││ └┘\n ││   \n └┘   \n",
      },
      {
        text: "ユ",
        prounounce: "yu",
        unicode: "\u30e6",
        art: "      \n ┌──┐ \n └─┐│ \n   ││ \n┌──┘└┐\n└────┘\n",
      },
      {
        text: "ヨ",
        prounounce: "yo",
        unicode: "\u30e8",
        art: "┌────┐\n└───┐│\n┌───┘│\n└───┐│\n┌───┘│\n└────┘\n",
      },
      {
        text: "ラ",
        prounounce: "ra",
        unicode: "\u30e9",
        art: " ┌──┐ \n └──┘ \n┌────┐\n└───┐│\n ┌──┘┘\n └──┘ \n",
      },
      {
        text: "リ",
        prounounce: "ri",
        unicode: "\u30ea",
        art: " ┌┐ ┌┐\n ││ ││\n ││ ││\n └┘ ││\n  ┌─┘│\n  └──┘\n",
      },
      {
        text: "ル",
        prounounce: "ru",
        unicode: "\u30eb",
        art: "   ┌┐  \n ┌┐││  \n ││││  \n ││││  \n┌┘┘│└┐ \n└┘ └─┘ \n",
      },
      {
        text: "レ",
        prounounce: "re",
        unicode: "\u30ec",
        art: "┌┐    \n││    \n││  ┌┐\n││ ┌┌┘\n│└─┌┘ \n└──┘  \n",
      },
      {
        text: "ロ",
        prounounce: "ro",
        unicode: "\u30ed",
        art: "┌────┐\n│┌──┐│\n││  ││\n││  ││\n│└──┘│\n└────┘\n",
      },
      {
        text: "ワ",
        prounounce: "wa",
        unicode: "\u30ef",
        art: "┌────┐\n│┌──┐│\n└┘  ││\n    ││\n   ┌┘│\n   └─┘\n",
      },
      {
        text: "ヲ",
        prounounce: "wo",
        unicode: "\u30f2",
        art: "┌────┐\n└───┐│\n┌───┘│\n└───┐│\n  ┌─┘┘\n  └─┘ \n",
      },
      {
        text: "ン",
        prounounce: "n",
        unicode: "\u30f3",
        art: "    ┌┐\n┌──┐││\n└──┘││\n    ││\n┌───┘│\n└────┘\n",
      },
      // 濁音
      {
        text: "ガ",
        prounounce: "ga",
        unicode: "\u30ac",
        art: " ┌┐┌┬┐\n┌┘└└┴┤\n└┐┌─┐│\n ││ ││\n┌┘┘┌┘│\n└┘ └─┘\n",
      },
      {
        text: "ギ",
        prounounce: "gi",
        unicode: "\u30ae",
        art: "  ┌┬┬┐\n┌─┘└┴┤\n└─┐┌─┘\n┌─┘└─┐\n└─┐┌─┘\n  └┘  \n",
      },
      {
        text: "グ",
        prounounce: "gu",
        unicode: "\u30b0",
        art: "┌┐ ┌┬┐\n│└─└┼┘\n│┌─┐│ \n└┘ ││ \n  ┌┘│ \n  └─┘ \n",
      },
      {
        text: "ゲ",
        prounounce: "ge",
        unicode: "\u30b2",
        art: "┌┐ ┌┬┐\n│└─└┴┤\n│┌─┐┌┘\n└┘ ││ \n   ││ \n   └┘ \n",
      },
      {
        text: "ゴ",
        prounounce: "go",
        unicode: "\u30b4",
        art: "   ┌┬┐\n┌──└┴┤\n└───┐│\n    ││\n┌───┘│\n└────┘\n",
      },
      {
        text: "ザ",
        prounounce: "za",
        unicode: "\u30b6",
        art: "   ┌┬┐\n ┌┐├┼┘\n┌┘└┘└┐\n└┐┌┐┌┘\n └┘││ \n   └┘ \n",
      },
      {
        text: "ジ",
        prounounce: "ji",
        unicode: "\u30b8",
        art: "   ┌┬┐\n┌──└┴┤\n├──┤││\n└──┘││\n┌───┘│\n└────┘\n",
      },
      {
        text: "ズ",
        prounounce: "zu",
        unicode: "\u30ba",
        art: "┌──┌┬┐\n└──┐┴┤\n  ┌┘┌ \n ┌┘┬└┐\n┌┘┘└┐│\n└┘  └┘\n",
      },
      {
        text: "ゼ",
        prounounce: "ze",
        unicode: "\u30bc",
        art: " ┌┐┌┬┐\n┌┘└└┴┤\n└┐┌─┐│\n ││ └┘\n │└──┐\n └───┘\n",
      },
      {
        text: "ゾ",
        prounounce: "zo",
        unicode: "\u30be",
        art: "┌┐ ┌┬┐\n└└┐└┴┤\n └┘ ││\n   ┌┘┘\n ┌─┘┘ \n └─┘  \n",
      },
      {
        text: "ダ",
        prounounce: "da",
        unicode: "\u30c0",
        art: "┌──┌┬┐\n│┌──┴┤\n││┌─┘│\n└┘└─┐│\n   ┌┘│\n   └─┘\n",
      },
      {
        text: "ヂ",
        prounounce: "ji",
        unicode: "\u30c2",
        art: " ┌─┌┬┐ \n └┐└┴┘\n┌─┘└─┐\n└─┐┌─┘\n ┌┘┘  \n └┘   \n",
      },
      {
        text: "ヅ",
        prounounce: "zu",
        unicode: "\u30c5",
        art: "   ┌┬┐\n┌┐┌└┴┤\n││││││\n└┘└┘││\n┌───┘│\n└────┘\n",
      },
      {
        text: "デ",
        prounounce: "de",
        unicode: "\u30c7",
        art: " ┌─┌┬┐\n └─└┴┘\n┌────┐\n└─┐┌─┘\n ┌┘┘  \n └┘   \n",
      },
      {
        text: "ド",
        prounounce: "do",
        unicode: "\u30c9",
        art: " ┌─┬┬┐\n │ ├┴┘\n │ └─┐\n │ ┌─┘\n │ │  \n └─┘  \n",
      },
      {
        text: "バ",
        prounounce: "ba",
        unicode: "\u30D0",
        art: "   ┌┬┐\n ┌┐├┼┘\n ││││ \n │││└┐\n┌┘┘└┐│\n└┘  └┘\n",
      },
      {
        text: "ビ",
        prounounce: "bi",
        unicode: "\u30D3",
        art: "┌┐ ┌┬┐\n││ └┴┘\n│└───┐\n│┌───┘\n│└───┐\n└────┘\n",
      },
      {
        text: "ブ",
        prounounce: "bu",
        unicode: "\u30D6",
        art: "   ┌┬┐\n┌──┴┴┤\n└───┐│\n   ┌┘┘\n  ┌┘┘ \n  └┘  \n",
      },
      {
        text: "ベ",
        prounounce: "be",
        unicode: "\u30D9",
        art: "   ┌┬┐\n ┌─┼┴┘\n┌┘─└┐ \n││ └└┐\n└┘  ││\n    └┘\n",
      },
      {
        text: "ボ",
        prounounce: "bo",
        unicode: "\u30DC",
        art: "  ┌┬┬┐\n┌─┘└┴┤\n└─┐┌─┘\n┌┐││┌┐\n││││││\n└┘└┘└┘\n",
      },
      // 半濁音
      {
        text: "パ",
        prounounce: "pa",
        unicode: "\u30D1",
        art: "    ┌┐\n ┌┐┌└┘\n ││││ \n │││└┐\n┌┘┘└┐│\n└┘  └┘\n",
      },
      {
        text: "ピ",
        prounounce: "pi",
        unicode: "\u30D4",
        art: "┌┐  ┌┐\n││  └┘\n│└───┐\n│┌───┘\n│└───┐\n└────┘\n",
      },
      {
        text: "プ",
        prounounce: "pu",
        unicode: "\u30D7",
        art: "    ┌┐\n┌───└┘\n└───┐│\n   ┌┘┘\n  ┌┘┘ \n  └┘   \n",
      },
      {
        text: "ペ",
        prounounce: "pe",
        unicode: "\u30DA",
        art: "    ┌┐\n ┌─┐└┘\n┌┘─└┐ \n││ └└┐\n└┘  ││\n   └┘\n",
      },
      {
        text: "ポ",
        prounounce: "po",
        unicode: "\u30DD",
        art: "  ┌┐┌┐\n┌─┘└└┘\n└─┐┌─┘\n┌┐││┌┐\n││││││\n└┘└┘└┘\n",
      },
      // 小文字
      {
        text: "ァ",
        prounounce: "xa",
        unicode: "\u30a1",
        art: " ┌───┐\n └──┐│\n  ┌┐└┘\n  ││  \n  └┘  \n",
      },
      {
        text: "ィ",
        prounounce: "xi",
        unicode: "\u30a3",
        art: "      \n        ┌┐\n┌─┘│\n└┐┌┘\n    ││   \n    └┘   \n",
      },
      {
        text: "ェ",
        prounounce: "xe",
        unicode: "\u30a7",
        art: "   ┌──┐\n   └┐┌┘\n   ┌┘└┐\n   └──┘\n",
      },
      // 拗音
      {
        text: "ャ",
        prounounce: "small_ya",
        unicode: "\u30e3",
        art: "      \n  ┌┐  \n ┌┘└─┐\n └┐┌┐│\n  ││└┘\n  └┘  \n",
      },
      {
        text: "ュ",
        prounounce: "small_yu",
        unicode: "\u30e5",
        art: "      \n  ┌─┐ \n  └┐│ \n  ┌┘└┐\n  └──┘\n",
      },
      {
        text: "ョ",
        prounounce: "small_yo",
        unicode: "\u30e7",
        art: "      \n  ┌──┐\n  ├─ │\n  ├─ │\n  └──┘\n",
      },
      // 促音
      {
        text: "ッ",
        prounounce: "small_tsu",
        unicode: "\u30C3",
        art: "      \n      \n ┌┬┐┌┐\n └┴┘││\n ┌──┘│\n └───┘\n",
      },
    ],
  },
];
